### ISSUE TITLE
[server] 스프링 프레임워크 핵심 기술: 진행 사항 공유

### ISSUE THREAD

**Issue by junbly** [z-nine/seat-common#5]
## 스터디 개인별 진행 사항 공유
- 아래 내용 복사하여 댓글로 공유
- 강의 시청했으면 체크

```
### IoC 컨테이너와 빈
- [ ] IoC 컨테이너 1부: 스프링 IoC 컨테이너와 빈 (00:15:00)
- [ ] IoC 컨테이너 2부: ApplicationContext와 다양한 빈 설정 방법 (00:18:00)
- [ ] IoC 컨테이너 3부: @Autowire (00:23:00)
- [ ] IoC 컨테이너 4부: @Component와 컴포넌트 스캔 (00:14:00)
- [ ] IoC 컨테이너 5부: 빈의 스코프 (00:14:00)
- [ ] IoC 컨테이너 6부: Environment 1부. 프로파일 (00:11:00)
- [ ] IoC 컨테이너 6부: Environment 2부. 프로퍼티 (00:05:00)
- [ ] IoC 컨테이너 7부: MessageSource (00:08:00)
- [ ] IoC 컨테이너 8부: ApplicationEventPublisher (00:13:00)
- [ ] IoC 컨테이너 9부: ResourceLoader (00:06:00)
### Resource / Validation
- [ ] Resource 추상화 (00:15:00)
- [ ] Validation 추상화 (00:17:00)

### 데이터 바인딩
- [ ] 데이터 바인딩 추상화: PropertyEditor (00:13:00)
- [ ] 데이터 바인딩 추상화: Converter와 Formatter (00:25:00)

### SpEL
- [ ] SpEL (스프링 Expression Language) (00:15:00)

### 스프링 AOP
- [ ] 스프링 AOP: 개념 소개 (00:18:00)
- [ ] 스프링 AOP: 프록시 기반 AOP (00:18:00)
- [ ] 스프링 AOP: @AOP (00:13:00)

### Null-Safety
- [ ] Null-safety (00:06:00)

### 마무리
- [ ] outro (00:07:00)
```

**Comment by Junhyeon2** [comment]
### IoC 컨테이너와 빈
- [ ] IoC 컨테이너 1부: 스프링 IoC 컨테이너와 빈 (00:15:00)
- [ ] IoC 컨테이너 2부: ApplicationContext와 다양한 빈 설정 방법 (00:18:00)
- [ ] IoC 컨테이너 3부: @Autowire (00:23:00)
- [ ] IoC 컨테이너 4부: @Component와 컴포넌트 스캔 (00:14:00)
- [ ] IoC 컨테이너 5부: 빈의 스코프 (00:14:00)
- [ ] IoC 컨테이너 6부: Environment 1부. 프로파일 (00:11:00)
- [ ] IoC 컨테이너 6부: Environment 2부. 프로퍼티 (00:05:00)
- [ ] IoC 컨테이너 7부: MessageSource 00:08:00
- [ ] IoC 컨테이너 8부: ApplicationEventPublisher (00:13:00)
- [ ] IoC 컨테이너 9부: ResourceLoader (00:06:00)
### Resource / Validation
- [ ] Resource 추상화 (00:15:00)
- [ ] Validation 추상화 (00:17:00)

### 데이터 바인딩
- [ ] 데이터 바인딩 추상화: PropertyEditor (00:13:00)
- [ ] 데이터 바인딩 추상화: Converter와 Formatter (00:25:00)

### SpEL
- [ ] SpEL (스프링 Expression Language) (00:15:00)

### 스프링 AOP
- [ ] 스프링 AOP: 개념 소개 (00:18:00)
- [ ] 스프링 AOP: 프록시 기반 AOP (00:18:00)
- [ ] 스프링 AOP: @AOP (00:13:00)

### Null-Safety
- [ ] Null-safety (00:06:00)

### 마무리
- [ ] outro (00:07:00)

**Comment by kwonjunbeom** [comment]
### IoC 컨테이너와 빈
- [ ] IoC 컨테이너 1부: 스프링 IoC 컨테이너와 빈 (00:15:00)
- [ ] IoC 컨테이너 2부: ApplicationContext와 다양한 빈 설정 방법 (00:18:00)
- [ ] IoC 컨테이너 3부: @Autowire (00:23:00)
- [ ] IoC 컨테이너 4부: @Component와 컴포넌트 스캔 (00:14:00)
- [ ] IoC 컨테이너 5부: 빈의 스코프 (00:14:00)
- [ ] IoC 컨테이너 6부: Environment 1부. 프로파일 (00:11:00)
- [ ] IoC 컨테이너 6부: Environment 2부. 프로퍼티 (00:05:00)
- [ ] IoC 컨테이너 7부: MessageSource 00:08:00
- [ ] IoC 컨테이너 8부: ApplicationEventPublisher (00:13:00)
- [ ] IoC 컨테이너 9부: ResourceLoader (00:06:00)
### Resource / Validation
- [ ] Resource 추상화 (00:15:00)
- [ ] Validation 추상화 (00:17:00)

### 데이터 바인딩
- [ ] 데이터 바인딩 추상화: PropertyEditor (00:13:00)
- [ ] 데이터 바인딩 추상화: Converter와 Formatter (00:25:00)

### SpEL
- [ ] SpEL (스프링 Expression Language) (00:15:00)

### 스프링 AOP
- [ ] 스프링 AOP: 개념 소개 (00:18:00)
- [ ] 스프링 AOP: 프록시 기반 AOP (00:18:00)
- [ ] 스프링 AOP: @AOP (00:13:00)

### Null-Safety
- [ ] Null-safety (00:06:00)

### 마무리
- [ ] outro (00:07:00)

**Comment by SeoJeongHan** [comment]
### IoC 컨테이너와 빈
- [ ] IoC 컨테이너 1부: 스프링 IoC 컨테이너와 빈 (00:15:00)
- [ ] IoC 컨테이너 2부: ApplicationContext와 다양한 빈 설정 방법 (00:18:00)
- [ ] IoC 컨테이너 3부: @Autowire (00:23:00)
- [ ] IoC 컨테이너 4부: @Component와 컴포넌트 스캔 (00:14:00)
- [ ] IoC 컨테이너 5부: 빈의 스코프 (00:14:00)
- [ ] IoC 컨테이너 6부: Environment 1부. 프로파일 (00:11:00)
- [ ] IoC 컨테이너 6부: Environment 2부. 프로퍼티 (00:05:00)
- [ ] IoC 컨테이너 7부: MessageSource 00:08:00
- [ ] IoC 컨테이너 8부: ApplicationEventPublisher (00:13:00)
- [ ] IoC 컨테이너 9부: ResourceLoader (00:06:00)
### Resource / Validation
- [ ] Resource 추상화 (00:15:00)
- [ ] Validation 추상화 (00:17:00)

### 데이터 바인딩
- [ ] 데이터 바인딩 추상화: PropertyEditor (00:13:00)
- [ ] 데이터 바인딩 추상화: Converter와 Formatter (00:25:00)

### SpEL
- [ ] SpEL (스프링 Expression Language) (00:15:00)

### 스프링 AOP
- [ ] 스프링 AOP: 개념 소개 (00:18:00)
- [ ] 스프링 AOP: 프록시 기반 AOP (00:18:00)
- [ ] 스프링 AOP: @AOP (00:13:00)

### Null-Safety
- [ ] Null-safety (00:06:00)

### 마무리
- [ ] outro (00:07:00)

**Comment by chro1** [comment]
### IoC 컨테이너와 빈
- [ ] IoC 컨테이너 1부: 스프링 IoC 컨테이너와 빈 (00:15:00)
- [ ] IoC 컨테이너 2부: ApplicationContext와 다양한 빈 설정 방법 (00:18:00)
- [ ] IoC 컨테이너 3부: @Autowire (00:23:00)
- [ ] IoC 컨테이너 4부: @Component와 컴포넌트 스캔 (00:14:00)
- [ ] IoC 컨테이너 5부: 빈의 스코프 (00:14:00)
- [ ] IoC 컨테이너 6부: Environment 1부. 프로파일 (00:11:00)
- [ ] IoC 컨테이너 6부: Environment 2부. 프로퍼티 (00:05:00)
- [ ] IoC 컨테이너 7부: MessageSource (00:08:00)
- [ ] IoC 컨테이너 8부: ApplicationEventPublisher (00:13:00)
- [ ] IoC 컨테이너 9부: ResourceLoader (00:06:00)
### Resource / Validation
- [ ] Resource 추상화 (00:15:00)
- [ ] Validation 추상화 (00:17:00)

### 데이터 바인딩
- [ ] 데이터 바인딩 추상화: PropertyEditor (00:13:00)
- [ ] 데이터 바인딩 추상화: Converter와 Formatter (00:25:00)

### SpEL
- [ ] SpEL (스프링 Expression Language) (00:15:00)

### 스프링 AOP
- [ ] 스프링 AOP: 개념 소개 (00:18:00)
- [ ] 스프링 AOP: 프록시 기반 AOP (00:18:00)
- [ ] 스프링 AOP: @AOP (00:13:00)

### Null-Safety
- [ ] Null-safety (00:06:00)

### 마무리
- [ ] outro (00:07:00)
